---
title: "surv-ml"
output: html_document
---

# Machine Learning Survival Models

Todo:

 - Fit basic random survival forests
 - test out some different parameters plus explanations
 - Compare fit of the model to cph models.  concordance??
 - bayesian parameter search???

## Random Survival Forests with Ranger

```{r}
install.packages("ranger")
library(ranger)
```


```{r}
stree <- ranger(Surv(week, arrest) ~ fin + age + race + wexp + mar + paro + prio,
                data = rossi,
                num.trees = 1000,
                importance = "permutation",
                splitrule = "extratrees",
                seed = 43)

death_times = stree$unique.death.times
surv_prob = data.frame(stree$survival)
avg_prob = sapply(surv_prob, mean)

plot(death_times, avg_prob, type = "s")

plot(death_times, avg_prob,
     type = "s",
     ylim = c(0.7,1),
     col = "red", lwd = 2, bty = "n",
     ylab = "Survival Probability", xlab = "Time in Months",
     main = "Survival Tree Model\nAverage Survival Curve")
 


```
